name: Release

on:
  push:
    branches:
      - main  # 你可以根据需要更改触发条件
  pull_request:
    branches:
      - main  # 你可以根据需要更改触发条件
  workflow_dispatch:  # 允许手动触发

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'

    - name: Enable Go Modules and Download Dependencies
      run: |
        go mod tidy
        go mod download

    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        echo "$GOPATH/bin" >> $GITHUB_PATH

    - name: Install Docker
      run: |
        sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.33.1/docker-compose-linux-aarch64" -o /usr/bin/docker-compose
        sudo chmod +x /usr/bin/docker-compose

    - name: Build and Release
      run: make release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-artifacts
        path: |
          ./bin/StealthIMDB
          ./bin/StealthIMDB.exe
          ./bin/StealthIMDB.docker.zst
